### ISSUE TITLE
is it possible to play faster than realtime and to record to a .wav file ?

### ISSUE THREAD

**Issue by cyberic99** [raysan5/raudio#10]
Hello

I'm using raudio for a project, and I would like to have the ability to 'render' a wav file faster than realtime.

What I have done for now is to modify raudio_standalone.c example, and save the pFramesOut content to wav, at the end of OnSendAudioDataToDevice.
So I can save raylib output to .wav, but the rendering time is still the real time.

What I'd like to do now is to call OnSendAudioDataToDevice() manually, and save the output data to .wav.
When I tried this, I get some output but it sounds like very small buffers repeated again and again.

Is there anything else I have to do to 'simulate' the callback from miniAudio, except calling it ?

Thanks for you help

**Comment by raysan5** [comment]
@cyberic99 It depends on what you are trying to do but you can load the full file as a `Wave` and just process it manually. 

Once processed, it can be saved as a `.wav` or `.qoa` with `ExportWave()`.

**Comment by cyberic99** [comment]
Hello @raysan5 maybe I wasn't clear enough.
I'd like to use raudio to mix different sounds together, and save the result to wave.
And I would like to do it as fast as possible

**Comment by raysan5** [comment]
@cyberic99 Then, the fastest way to do it is just load all required sound data as `Wave`, mix it and save the result with with `ExportWave()`. This is the fastest way.

**Comment by cyberic99** [comment]
thank you @raysan5 . I found no way to call raudio mixing routines programmatically without calling ``InitAudioDevice()``, is there a way ?

**Comment by raysan5** [comment]
@cyberic99 No, you must call `InitAudioDevice()` first if using mixing routines.
