### ISSUE TITLE
Is it possible to build as a DLL?

### ISSUE THREAD

**Issue by sokolas** [raysan5/raudio#11]
I'm trying to build raudio as a DLL to use in my project with GCC 12.2.0 on MSYS2 mingw64:
`gcc -DRAUDIO_STANDALONE -DSUPPORT_FILEFORMAT_WAV -DSUPPORT_FILEFORMAT_OGG -DSUPPORT_FILEFORMAT_MP3 -DSUPPORT_FILEFORMAT_FLAC -Wall raudio.c -shared -o raudio.dll`
However, the result DLL doesn't have any exports according to `dumpbin`:
```
  Section contains the following exports for raudio.dll

    00000000 characteristics
    64C4D182 time date stamp Sat Jul 29 10:44:50 2023
        0.00 version
           1 ordinal base
           0 number of functions
           0 number of names
```
What would be the correct way to build it as a shared DLL?

**Comment by sokolas** [comment]
Turns out I have to define `SUPPORT_MODULE_RAUDIO` as well

**Comment by raysan5** [comment]
@sokolas Oh, actually it should be enabled automatically in standalone mode!
