### ISSUE TITLE
AudioProcessor in Music Streaming mode returns to SIGSEGV

### ISSUE THREAD

**Issue by tretdm** [raysan5/raudio#19]
The main problem is how to inform the main thread about the music stream update, because the option to add an audio processor does not work at all for me.

`SetAudioStreamCallback` function works correctly, since there is no possibility of iterating over callbacks.

_Tested in GCC 12.2.0, Debian 12 (bookworm)_

![изображение](https://github.com/raysan5/raudio/assets/76806170/73715abe-db65-423b-b387-857f9302dc35)

From my code:
```cpp
void AudioDecoder::output(char* pFileName) {
    // initializing MusicStream with LoadMusicStream function
    gStreamTs = new StreamTimestamp();
    gSpectrum = new AudioSpectrum();
    SetMasterVolume(1.0);
    PlayMusicStream(gMusic);
    AttachAudioStreamProcessor(gMusic.stream, audioCallback);
    while(true) {
       UpdateMusicStream(gMusic);
    }
}    

void AudioDecoder::audioCallback(void *bufferData, unsigned int frames) {
     /* Callback is here, regardless of the structure, 
      * we get SIGSEGV at the input of this pointer.       */
}
```

**Comment by tretdm** [comment]
The problem was that the path to the file was not specified there. For a long time I could not understand why.

I'm sorry for the trouble.

**Comment by raysan5** [comment]
@tretdm Glad you found the issue! Thanks for the update!
