### ISSUE TITLE
matching raudio to raylib 4.5v

### ISSUE THREAD

**Issue by sDos280** [raysan5/raudio#8]
it seem that raudio mismatch with the raylib main branch

**Comment by raysan5** [comment]
Oh! I did not update this repo! Feel free to send a PR!

**Comment by sDos280** [comment]
ok. Is updating the repo just like copping the raylib/raudio.c to raudio/raudio.c?

**Comment by sDos280** [comment]
Is there also a need to update the header?

**Comment by raysan5** [comment]
@sDos280 Yeah, `raudio.h` also needs to be reviewed.
